In [68]:
import numpy as np
import matplotlib.pyplot as plt

### Домашнее задание №0 - Основные математические понятия
### Задание 1.
Представить фильмы в виде бинарных векторов (numpy array) используюя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

Игра в имитацию [https://www.kinopoisk.ru/film/635772/]
Ярость [https://www.kinopoisk.ru/film/740644/]
12 лет рабства [https://www.kinopoisk.ru/film/606646/]
Однажды в Голливуде [https://www.kinopoisk.ru/film/1047883/]

In [43]:
a = np.array([0,0,0,0,1,0])
b = np.array([0,1,0,1,0,0])
c = np.array([0,0,1,0,0,0])
d = np.array([1,0,0,1,0,1])

### Задание 2.
Вычислить Евклидову норму каждого из векторов, полученных в Задании 1.

In [20]:
print(np.linalg.norm(a))
print(np.linalg.norm(b))
print(np.linalg.norm(c))
print(np.linalg.norm(d))

1.0
1.4142135623730951
1.0
1.7320508075688772


### Задание 3.
Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [30]:
np.rad2deg(np.arccos(np.dot(b,c) / np.linalg.norm(b) * np.linalg.norm(c)))

90.0

### Задание 4.
Объединить векторы, полученные в Задании 1 в матрицу, где каждый вектор является строкой матрицы. Полученную матрицу умножить на вектор [1,2,3,4]

In [65]:
m = np.array([a,b,c,d])
m = m.transpose()
m

array([[0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 1]])

In [66]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [67]:
total = m.dot(x)
total

array([4, 2, 3, 6, 1, 4])

### Задание 5.
Вычислить на бумаге и с помощью Python значение первой и второй производной для функции 3*x*(x**2 + x)**3   в точке x = 1


In [71]:
from sympy import *
import numpy as np

x = Symbol('x')
y = 3*x*(x**2 + x)**3

yprime = y.diff(x)
print(yprime)

3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3


In [75]:
from sympy import *
import numpy as np

x = Symbol('x')
y2 = 3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3

yprime2 = y2.diff(x)
print(yprime2)

3*x*(4*x + 2)*(6*x + 3)*(x**2 + x) + 18*x*(x**2 + x)**2 + 6*(6*x + 3)*(x**2 + x)**2


In [80]:
x = 1
print(3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3)


132


In [82]:
x = 1
print(3*x*(4*x + 2)*(6*x + 3)*(x**2 + x) + 18*x*(x**2 + x)**2 + 6*(6*x + 3)*(x**2 + x)**2)


612
